<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "parser"
 *
 * Auto generated by Extension Builder 2020-01-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'My Parser',
    'description' => 'a simple parser',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
],
'autoload' =>
    array (
        'psr-4' =>
            array (
                'cm\\parser\\' => 'Classes',
            ),
    ),
    '_md5_values_when_last_written' => 'a:0:{}',
    'suggests' => array(
),
];
